DROP TABLE IF EXISTS user_entity;

CREATE TABLE user_entity_jdbc
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name     VARCHAR(255),
    username VARCHAR(255),
    email    VARCHAR(255),
    quote    VARCHAR(255)
);